### ISSUE TITLE
use_pool为数字时报错

### ISSUE THREAD

**Issue by sylingd** [swlib/saber#9]
测试脚本：

```php
go(function () {
    $pool = Saber::create([
        'base_uri' => 'http://www.qq.com',
        'use_pool' => 10
    ]);
    var_dump($pool->get('/')->success);
});
```

错误信息：

```
Fatal error: Uncaught InvalidArgumentException: Host should not be empty! in /web/wwwroot/test/vendor/swlib/saber/src/Request.php:118
Stack trace:
#0 /web/wwwroot/test/vendor/swlib/saber/src/Request.php(152): Swlib\Saber\Request->getConnectionTarget()
#1 /web/wwwroot/test/vendor/swlib/saber/src/Saber.php(446): Swlib\Saber\Request->withPool(10)
#2 /web/wwwroot/test/vendor/swlib/saber/src/Saber.php(378): Swlib\Saber::transOptionsToRequest(Array, Object(Swlib\Saber\Request))
#3 /web/wwwroot/test/vendor/swlib/saber/src/Saber.php(145): Swlib\Saber->setOptions(Array, Object(Swlib\Saber\Request))
#4 /web/wwwroot/test/vendor/swlib/saber/src/Saber.php(108): Swlib\Saber->__construct(Array)
#5 /web/wwwroot/test/test.php(14): Swlib\Saber::create(Array)
#6 {main}
  thrown in /web/wwwroot/test/vendor/swlib/saber/src/Request.php on line 118
```

use_pool不为数字时则正常，简单看了一下是因为Request.php里面处理不一样：
```php
        if (is_numeric($this->use_pool)) {
            // limit max num
            ClientPool::getInstance()->setMaxEx($this->getConnectionTarget(), $bool_or_max_size);
        }
```

**Comment by twose** [comment]
抱歉, 配置转换中`use_pool`放的太前面了, 此时`base_uri`配置还未解析, 导致报错.
