### ISSUE TITLE
能否考虑支持下 IPv6 HTTP 请求

### ISSUE THREAD

**Issue by PrintNow** [swlib/saber#93]
我这里测试似乎是不支持 IPv6 HTTP 请求的，直接报错，测试的域名是 ipv6.hu60.cn

```
root@Chuwen:/opt/www/wwwroot# php run/1.php
PHP Fatal error:  Uncaught Swlib\Http\Exception\ConnectException: HTTP -1 Unknown: Connect timeout! the server is not listening on the port or the network is missing! in /opt/www/wwwroot/vendor/swlib/saber/src/Request.php:704
Stack trace:
#0 /opt/www/wwwroot/vendor/swlib/saber/src/RequestQueue.php(119): Swlib\Saber\Request->recv()
#1 /opt/www/wwwroot/vendor/swlib/saber/src/Saber.php(279): Swlib\Saber\RequestQueue->recv()
#2 /opt/www/wwwroot/vendor/swlib/saber/src/SaberGM.php(90): Swlib\Saber->requests()
#3 /opt/www/wwwroot/run/1.php(18): Swlib\SaberGM::requests()
#4 {main}
  thrown in /opt/www/wwwroot/vendor/swlib/saber/src/Request.php on line 704

Fatal error: Uncaught Swlib\Http\Exception\ConnectException: HTTP -1 Unknown: Connect timeout! the server is not listening on the port or the network is missing! in /opt/www/wwwroot/vendor/swlib/saber/src/Request.php:704
Stack trace:
#0 /opt/www/wwwroot/vendor/swlib/saber/src/RequestQueue.php(119): Swlib\Saber\Request->recv()
#1 /opt/www/wwwroot/vendor/swlib/saber/src/Saber.php(279): Swlib\Saber\RequestQueue->recv()
#2 /opt/www/wwwroot/vendor/swlib/saber/src/SaberGM.php(90): Swlib\Saber->requests()
#3 /opt/www/wwwroot/run/1.php(18): Swlib\SaberGM::requests()
#4 {main}
  thrown in /opt/www/wwwroot/vendor/swlib/saber/src/Request.php on line 704
```

测试代码：
```
<?php
include_once dirname(__DIR__) . "/vendor/autoload.php";

use Swlib\SaberGM;

co::set(['max_coroutine' => 8191]);

go(function () {
    $requests = [];
    for ($i = 2; $i--;) {
        $requests[] = ['uri' => 'https://ipv6.hu60.cn'];
    }

    $res = SaberGM::requests($requests);

    foreach ($res->getArrayCopy() as $v){
        $time = sprintf("%.2f", $v->time*1000);
        echo "状态码：{$v->statusCode}，耗时：{$time}\n";
    }

    echo "use {$res->time}s\n";
    echo "success: $res->success_num, error: $res->error_num";
});
```

**Comment by sy-records** [comment]
用的协程Client，是支持ipv6的...  这个网址没解析吧
![image](https://user-images.githubusercontent.com/33931153/83014781-e1d74c80-a051-11ea-98be-53c344af3ce1.png)

**Comment by PrintNow** [comment]
@sy-records 那你试试这个 `cron.iton.pw`：
```
C:\Users\chuwen>ping cron.iton.pw

正在 Ping nas.iton.pw [2409:8a38:6821:2990:c8f8:1555:c7f3:9d58] 具有 32 字节的数据:
来自 2409:8a38:6821:2990:c8f8:1555:c7f3:9d58 的回复: 时间<1ms
来自 2409:8a38:6821:2990:c8f8:1555:c7f3:9d58 的回复: 时间<1ms
来自 2409:8a38:6821:2990:c8f8:1555:c7f3:9d58 的回复: 时间<1ms
来自 2409:8a38:6821:2990:c8f8:1555:c7f3:9d58 的回复: 时间<1ms

2409:8a38:6821:2990:c8f8:1555:c7f3:9d58 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 0ms，最长 = 0ms，平均 = 0ms
```

---

用官方的方法我试过，我这测试无效：
```
Co\run(function () {
    $client = new Swoole\Coroutine\Http\Client('cron.iton.pw', 80);
    $client->setHeaders([
        'Host' => 'cron.iton.pw',
        'User-Agent' => 'Chrome/49.0.2587.3',
        'Accept' => 'text/html,application/xhtml+xml,application/xml',
        'Accept-Encoding' => 'gzip',
    ]);
    $client->set(['timeout' => 1]);
    $client->get('/index.php');
    echo $client->body;
    $client->close();
});

//返回的结果是空的
```

但改成这样子是可以正常使用：
```
Co\run(function () {
    //此处 host 参数填该域名解析结果
    $client = new Swoole\Coroutine\Http\Client('2409:8a38:6821:2990:c8f8:1555:c7f3:9d58', 80);
    $client->setHeaders([
        'Host' => 'cron.iton.pw',//这里保持不变
        'User-Agent' => 'Chrome/49.0.2587.3',
        'Accept' => 'text/html,application/xhtml+xml,application/xml',
        'Accept-Encoding' => 'gzip',
    ]);
    $client->set(['timeout' => 1]);
    $client->get('/index.php');
    echo $client->body;
    $client->close();
});

//输出结果：当前时间戳
```

**Comment by PrintNow** [comment]
@sy-records 我尝试在 `\swlib\saber\src\ClientPool.php` 第26行后面加上这段代码：
```
        //如果不是 IP，则进行 DNS 查询记录值
        if (!filter_var($options['host'], FILTER_VALIDATE_IP)) {
            //查询域名的 A记录 和 AAAA记录 值
            $dnsQuery = dns_get_record($options['host'], DNS_A|DNS_AAAA);
            $dnsQueryResCount = count($dnsQuery);
            $tmp = $dnsQuery[rand(0, $dnsQueryResCount)];

            if($dnsQueryResCount > 0){
                if($tmp['type'] == 'A'){
                    $options['host'] = $tmp['ip'];
                }else{
                    $options['host'] = $tmp['ipv6'];
                }
            }
        }
```

成功运行是一个概率问题（我是新手，或许我改的地方不对
```
root@Chuwen:/opt/www/wwwroot# php run/1.php
状态码：200，耗时：36.64
状态码：200，耗时：15.89
use 0.12553215026855s
success: 2, error: 0
```

然后我再次运行，就没有成功的了：
```
root@Chuwen:/opt/www/wwwroot/cron.iton.pw# php run/1.php
PHP Fatal error:  Uncaught Swoole\Coroutine\Http\Client\Exception: host is empty in /opt/www/wwwroot/cron.iton.pw/vendor/swlib/saber/src/ClientPool.php:47
Stack trace:
#0 /opt/www/wwwroot/cron.iton.pw/vendor/swlib/saber/src/ClientPool.php(47): Swoole\Coroutine\Http\Client->__construct()
#1 /opt/www/wwwroot/cron.iton.pw/vendor/swlib/saber/src/Request.php(582): Swlib\Saber\ClientPool->createEx()
#2 /opt/www/wwwroot/cron.iton.pw/vendor/swlib/saber/src/RequestQueue.php(113): Swlib\Saber\Request->exec()
#3 /opt/www/wwwroot/cron.iton.pw/vendor/swlib/saber/src/Saber.php(279): Swlib\Saber\RequestQueue->recv()
#4 /opt/www/wwwroot/cron.iton.pw/vendor/swlib/saber/src/SaberGM.php(90): Swlib\Saber->requests()
#5 /opt/www/wwwroot/cron.iton.pw/run/1.php(33): Swlib\SaberGM::requests()
#6 {main}
  thrown in /opt/www/wwwroot/cron.iton.pw/vendor/swlib/saber/src/ClientPool.php on line 47

Fatal error: Uncaught Swoole\Coroutine\Http\Client\Exception: host is empty in /opt/www/wwwroot/cron.iton.pw/vendor/swlib/saber/src/ClientPool.php:47
Stack trace:
#0 /opt/www/wwwroot/cron.iton.pw/vendor/swlib/saber/src/ClientPool.php(47): Swoole\Coroutine\Http\Client->__construct()
#1 /opt/www/wwwroot/cron.iton.pw/vendor/swlib/saber/src/Request.php(582): Swlib\Saber\ClientPool->createEx()
#2 /opt/www/wwwroot/cron.iton.pw/vendor/swlib/saber/src/RequestQueue.php(113): Swlib\Saber\Request->exec()
#3 /opt/www/wwwroot/cron.iton.pw/vendor/swlib/saber/src/Saber.php(279): Swlib\Saber\RequestQueue->recv()
#4 /opt/www/wwwroot/cron.iton.pw/vendor/swlib/saber/src/SaberGM.php(90): Swlib\Saber->requests()
#5 /opt/www/wwwroot/cron.iton.pw/run/1.php(33): Swlib\SaberGM::requests()
#6 {main}
  thrown in /opt/www/wwwroot/cron.iton.pw/vendor/swlib/saber/src/ClientPool.php on line 47
```

**Comment by sy-records** [comment]
你swoole什么版本

**Comment by PrintNow** [comment]
@sy-records **4.4.16**
```
root@Chuwen:/opt/www/wwwroot# php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.16
Built => Apr  5 2020 12:50:33
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2r  26 Feb 2019
pcre => enabled
zlib => 1.2.8
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

**Comment by sy-records** [comment]
嗯好 晚些试试

**Comment by sy-records** [comment]
这个自己解析一下吧。。。DNS解析默认是ipv4，底层DNS用的gethostbynane，请求地址没有ipv4地址的话可能出错

**Comment by PrintNow** [comment]
那能不能麻烦你修改下，我尝试改你的代码，但是有时成功 有时失败
https://github.com/swlib/saber/issues/93#issuecomment-634633724

**Comment by sy-records** [comment]
我这里网络不支持ipv6，没法测试...

**Comment by twose** [comment]
dns_get_record是阻塞函数, 且DNS查询是非常危险的阻塞操作, 请使用Co::gethostbyname或Co::getaddrinfo来查询

**Comment by PrintNow** [comment]
@sy-records 好的，谢谢

**Comment by PrintNow** [comment]
@twose 好的，谢谢建议。当时提出这个 Issues 确实对这个框架和文档看不懂😅
现在我大概浏览了下 Http 请求代码 并结合文档，现在我大概知道怎么做了&使用
